replicaCount: 7

image:
  repository: 556935884579.dkr.ecr.eu-north-1.amazonaws.com/hk-test-image
  tag: "${{ github.sha }}"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  class: alb
  scheme: internet-facing
  targetType: ip
  listenPorts: '[{"HTTP": 80},{"HTTPS": 443}]'
  sslRedirect: "443"
  certificateARN: arn:aws:acm:eu-north-1:556935884579:certificate/ce001fc7-7561-4de9-983f-2314fb7e80e0
  host: krishna.sivadevops.cloud
  path: /
  pathType: Prefix

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

